### ISSUE TITLE
Dyskusja na temat utworzonego okna aplikacji i jego poprawki

### ISSUE THREAD

**Issue by danielw1210** [olalis/npgwisielec#12]
Przedyskutowanie przez cały zespół utworzonego okna oraz jego ewentualna edycja.

**Comment by olalis** [comment]
Chyba jest mały problem z wyświetlaniem ikonki w lewym górnym rogu okienka.

**Comment by danielw1210** [comment]
Faktycznie, dzięki za informacje, znalazłem już błąd. Gdy uda mi się go naprawić wrzucę poprawioną wersję.

**Comment by LukaszRams** [comment]
Mi napisy "HASŁO" i "PODAJ LITERĘ" obcina trochę z prawej strony

**Comment by LukaszRams** [comment]
linia 70
self.haslolabel.setGeometry(QtCore.QRect(40, 10, 80, 41))
font = QtGui.QFont()
font.setPointSize(14)
linia 52
self.podaj_btn.setGeometry(QtCore.QRect(65, 480, 125, 31))
U mnie to pomogło ale sprawdźcie czy u was też jest źle bo to może tylko u mnie

**Comment by olalis** [comment]
U mnie jest ten sam problem ale po zmianach zaproponowanych przez Łukasza wszystko wygląda tak jak należy.

**Comment by danielw1210** [comment]
Okej, różnice mogą wynikać z ustawień skalowania w Windowsie. U mnie na ustawieniu 100% wszystko wygląda dobrze. Zmienię to, aby osobom z ustawieniami na 125% dobrze się wyświetlało a na 100% czcionka będzie trochę mniejsza.

**Comment by danielw1210** [comment]
Poprawione, możecie sprawdzić jeszcze raz.

**Comment by LukaszRams** [comment]
U mnie teraz wszystko jest dobrze
Założę temat w wiki i dodam twoje spostrzeżenie
