### ISSUE TITLE
Przetestowanie poprawności działania bazy danych 

### ISSUE THREAD

**Issue by olalis** [olalis/npgwisielec#13]
Sprawdzenie poprawności tworzenia się bazy danych w programie oraz dodawania do niej danych z plików csv.

**Comment by olalis** [comment]
Do sprawdzenia czy do bazy dodawane są dane można użyć programu DB Browser for SQLite.

**Comment by danielw1210** [comment]
Sprawdziłem za pomocą tego programu i wszystko działa. Dodatkowo po zaktualizowania repozytorium podstawowa funkcjonalność również działa, poprawnie losując różne hasła na podstawie kategorii i poziomu trudności więc wszystko jest ok.
