### ISSUE TITLE
Uzupełnienie modelu bazy danych i jej funkcji 

### ISSUE THREAD

**Issue by olalis** [olalis/npgwisielec#17]

**Comment by LukaszRams** [comment]
Hej, analizowałem plik baza.py i nie zauważyłem czy jest tam jakaś funkcja która podczas zapisu przechowa wartości:
-wykorzystanych liter
-lb. prób
-pola zgadniete

**Comment by olalis** [comment]
Zapomniałam dodać tych parametrów do istniejącej już funkcji. 
Plik baza.py jest już poprawiony.
