### ISSUE TITLE
Dodanie funkcji obsługujących zapis/odczyt

### ISSUE THREAD

**Issue by olalis** [olalis/npgwisielec#19]

**Comment by olalis** [comment]
Wszystko działa poprawnie ale nie jestem pewna czy jest sens stosować zapis stanu gry do rejestru skoro mamy już stworzoną bazę danych. Może trzeba spróbować to poprawić? Dodałam potrzebne funkcje do pliku baza.py obsługujące zapis i odczyt danych z bazy, które będą pomocne jeśli będziesz chciał dokonać zmiany.

**Comment by LukaszRams** [comment]
Ok będę próbował to zmienić, jeśli mi się uda zaktualizuję plik
