### ISSUE TITLE
Testowanie i dyskusja 

### ISSUE THREAD

**Issue by olalis** [olalis/npgwisielec#21]

**Comment by LukaszRams** [comment]
Program został zaktualizowany, do wersji w której aktualny stan gry zostaje zapisany do bazy danych.
Powinien działać następująco:
-Nie da się zapisać nierozpoczętej gry (zostaje wyświetlony komunikat)
-Nie da się zapisać gry w momencie gdy zostanie wyświetlony komunikat o przegranej/wygranej
(zostaje wyświetlony ten sam komunikat co w pierwszym przypadku)
-Zapisaną grę można nadpisać w dowolnym momencie (z wyłączeniem powyższych przypadków)
-Grę można wczytać w dowolnym momencie(włącznie z przypadkiem pierwszym i drugim)
-Jeśli nie rozpoczęto gry, ani nie wczytano podanie litery kończy się stosownym komunikatem (zachowanie poprzedniej funkcjonalności)

**Comment by LukaszRams** [comment]
Wpadła kolejna aktualizacja!!!
Jeśli wczytamy lub rozpoczniemy grę i następnie wciśniemy zakończ pojawi się okno dialogowe czy chcemy zapisać grę:
Tak-zapisuje i zamyka
Nie-tylko zamyka (nie usuwa wcześniej zapisanej gry)
Uwaga!!!
Jeśli nie wczytamy ani nie rozpoczniemy gry, a naciśniemy zakończ, okno nie pojawi się a gra się nie zapisze (bo nie ma takiej potrzeby) i zamknie
Miłych testów

**Comment by danielw1210** [comment]
Myślę że dobrze byłoby też zmienić tytuł wyskakującego okna pytającego o zapisanie gry. Oraz przy funkcji obsługującej przyciski TAK oraz NIE usunąć najprawdopodobniej napisane w celu sprawdzenia działania linijki które wypisuje tak i nie w konsoli. 
To taka kosmetyka a reszta działa bez zastrzeżeń. :)
