### ISSUE TITLE
Sprawdzenie odczytu/zapisu stanu gry

### ISSUE THREAD

**Issue by olalis** [olalis/npgwisielec#24]

**Comment by LukaszRams** [comment]
Program został zaktualizowany, do wersji w której aktualny stan gry zostaje zapisany do bazy danych.
Powinien działać następująco:
-Nie da się zapisać nierozpoczętej gry (zostaje wyświetlony komunikat)
-Nie da się zapisać gry w momencie gdy zostanie wyświetlony komunikat o przegranej/wygranej
(zostaje wyświetlony ten sam komunikat co w pierwszym przypadku)
-Zapisaną grę można nadpisać w dowolnym momencie (z wyłączeniem powyższych przypadków)
-Grę można wczytać w dowolnym momencie(włącznie z przypadkiem pierwszym i drugim)
-Jeśli nie rozpoczęto gry, ani nie wczytano podanie litery kończy się stosownym komunikatem (zachowanie poprzedniej funkcjonalności)

**Comment by olalis** [comment]
Można jeszcze dodać komunikat informujący użytkownika o tym że zapis gry się powiódł w momencie gdy gra jeszcze trwa (np. wpisane zostały dopiero dwie litery)

**Comment by LukaszRams** [comment]
Dodałem komunikat
"Gra została poprawnie zapisana"
